#!/usr/bin/env python3
"""Regenerate examples/viz/gallery.html from the current qsv binary.

`gallery.html` is a lightweight, CDN-plotly page rendering every `qsv viz`
chart type from the sample datasets in this directory. It is a checked-in
*artifact*; this script is the source of truth for how it's produced.

For each figure it runs the documented `qsv viz` command, extracts the figure
JSON object that plotly-rs emits (`Plotly.newPlot(graph_div, {...})`) from the
self-contained output, and reassembles them into one page that loads plotly from
the CDN (so the committed file stays small). The static scaffold (head / style /
header) is reused verbatim from the existing gallery, so re-running this only
changes figure content and order.

Usage (from the repo root), after changing viz output or the datasets:

    cargo build --bin qsv -F all_features
    python3 examples/viz/gen_gallery.py

Set QSV_BIN to point at a specific binary; otherwise target/{debug,release}/qsv
or a `qsv` on PATH is used. Re-run and commit gallery.html if the diff is what
you expect. The per-figure commands below are mirrored in README.md.
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

VIZ_DIR = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(VIZ_DIR))
GALLERY = os.path.join(VIZ_DIR, "gallery.html")
MARKER = "Plotly.newPlot(graph_div, "

BANNER = (
    "<!-- AUTO-GENERATED by examples/viz/gen_gallery.py — do not edit by hand.\n"
    "     Regenerate (from the repo root) after changing viz output or the datasets:\n"
    "       cargo build --bin qsv -F all_features && python3 examples/viz/gen_gallery.py\n"
    "-->"
)

# (title, description, full_width, [viz args]) — or a 5th element [prep qsv args] to run a
# qsv command (e.g. moarstats) before the viz command, in the same dir. Order matters: the
# full-width smart dashboards lead and close the contiguous run of individual chart types.
FIGURES = [
    ("smart dashboard", "Auto-profiled overview: correlation heatmap + box plots + frequency bars.",
     True, ["smart", "sales_sample.csv", "--max-charts", "8"]),
    ("smart dashboard (moarstats-informed)",
     "Same auto-profiler, but after `qsv moarstats --advanced` has extended the stats cache: the "
     "bimodal monthly_spend column renders as a histogram (a box plot would hide its two peaks), "
     "and the skewed account_age_days box is annotated with its skew direction and outlier share.",
     True, ["smart", "customer_spend.csv", "--max-charts", "8"],
     ["moarstats", "--advanced", "customer_spend.csv"]),
    ("bar", "Revenue by region (aggregated sum).",
     False, ["bar", "sales_sample.csv", "--x", "region", "--y", "revenue", "--agg", "sum"]),
    ("line", "Closing price over time.",
     False, ["line", "stock_prices.csv", "--x", "date", "--y", "close"]),
    ("scatter", "Units sold vs revenue.",
     False, ["scatter", "sales_sample.csv", "--x", "units_sold", "--y", "revenue"]),
    ("scatter (bubble)", "Units vs revenue; marker size = shipping cost, color = profit margin %.",
     False, ["scatter", "sales_sample.csv", "--x", "units_sold", "--y", "revenue",
             "--size", "shipping_cost", "--color", "profit_margin_pct"]),
    ("histogram", "Distribution of unit price.",
     False, ["histogram", "sales_sample.csv", "--x", "unit_price"]),
    ("box", "Spread of revenue (Tukey whiskers; points beyond the fences shown as outliers).",
     False, ["box", "sales_sample.csv", "--y", "revenue"]),
    ("box (grouped)", "Revenue spread per region — real Tukey whiskers + every (jittered) point overlaid (--box-points all).",
     False, ["box", "sales_sample.csv", "--y", "revenue", "--x", "region", "--box-points", "all"]),
    ("pie (donut)", "Revenue share by product category.",
     False, ["pie", "sales_sample.csv", "--x", "product_category", "--y", "revenue", "--donut"]),
    ("heatmap (correlation)", "Pearson correlation matrix over numeric columns.",
     False, ["heatmap", "sales_sample.csv"]),
    ("scatter (correlated pair)",
     "The most strongly correlated numeric pair (discount_pct vs profit_margin_pct, r=-0.99). "
     "viz smart auto-adds this as a drill-down beside the correlation heatmap.",
     False, ["scatter", "sales_sample.csv", "--x", "discount_pct", "--y", "profit_margin_pct"]),
    ("heatmap (pivot)", "Region x category grid of revenue.",
     False, ["heatmap", "sales_sample.csv", "--x", "region", "--y", "product_category", "--z", "revenue"]),
    ("candlestick", "OHLC price action.",
     False, ["candlestick", "stock_prices.csv", "--x", "date", "--ohlc-open", "open",
             "--high", "high", "--low", "low", "--close", "close"]),
    ("ohlc", "Open-high-low-close bars.",
     False, ["ohlc", "stock_prices.csv", "--x", "date", "--ohlc-open", "open",
             "--high", "high", "--low", "low", "--close", "close"]),
    ("sankey", "Web session funnel (duplicate edges aggregated).",
     False, ["sankey", "web_flows.csv", "--source", "source", "--target", "target", "--value", "sessions"]),
    ("radar", "Multi-axis brand comparison (per-axis mean per series).",
     False, ["radar", "product_ratings.csv", "--cols", "battery,camera,performance,display,value,design",
             "--series", "brand"]),
    ("map", "Earthquake points on token-free OpenStreetMap tiles; marker color = magnitude, size = depth.",
     False, ["map", "quakes.csv", "--lat", "lat", "--lon", "lon", "--color", "magnitude", "--size", "depth_km"]),
    ("map (density)", "DensityMapbox heatmap of the same points on a light Carto basemap.",
     False, ["map", "quakes.csv", "--lat", "lat", "--lon", "lon", "--density", "--style", "carto-positron"]),
    ("smart dashboard (time-series)",
     "Auto dashboard for stock_prices: a time-series trend panel (the first numeric column over the "
     "date) leads, alongside box-plot summaries of the OHLC columns.",
     True, ["smart", "stock_prices.csv", "--max-charts", "8"]),
]


def find_qsv():
    if os.environ.get("QSV_BIN"):
        return os.environ["QSV_BIN"]
    for rel in ("target/debug/qsv", "target/release/qsv"):
        cand = os.path.join(REPO, rel)
        if os.path.exists(cand):
            return cand
    found = shutil.which("qsv")
    if found:
        return found
    sys.exit("qsv binary not found: build it (cargo build --bin qsv -F all_features) or set QSV_BIN")


def extract_fig_json(html):
    """Brace-scan the balanced {...} object after the plotly newPlot marker."""
    start = html.index(MARKER) + len(MARKER)
    assert html[start] == "{", f"expected object at {start}, got {html[start]!r}"
    depth, in_str, esc = 0, False, False
    for i in range(start, len(html)):
        c = html[i]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            continue
        if c == '"':
            in_str = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return json.loads(html[start:i + 1])
    raise ValueError("unbalanced braces after newPlot marker")


def run_fig(qsv, args, prep=None):
    # optional prep step (e.g. `qsv moarstats --advanced <file>`) that extends the stats cache
    # the following `viz smart` run reads; sidecars are cleaned up after all figures are built
    if prep:
        subprocess.run([qsv, *prep], cwd=VIZ_DIR, check=True, capture_output=True, text=True)
    fd, out = tempfile.mkstemp(suffix=".html")
    os.close(fd)
    try:
        subprocess.run([qsv, "viz", *args, "-o", out], cwd=VIZ_DIR,
                       check=True, capture_output=True, text=True)
        with open(out, encoding="utf-8") as fh:
            return extract_fig_json(fh.read())
    finally:
        os.unlink(out)


def cleanup_sidecars():
    # `viz smart` writes a stats cache next to the CSV, and `moarstats --advanced` auto-creates
    # an `.idx` index; don't leave either in the tree (the committed datasets ship without them)
    for f in os.listdir(VIZ_DIR):
        if ".stats.csv" in f or ".stats.jsonl" in f or f.endswith(".idx"):
            os.unlink(os.path.join(VIZ_DIR, f))


def main():
    qsv = find_qsv()
    # reuse the existing scaffold verbatim: everything up to and including `<div class="grid">`,
    # minus any previous banner (re-added below so it stays a single, current copy)
    with open(GALLERY, encoding="utf-8") as fh:
        existing = fh.read()
    head = existing[: existing.index('<div class="grid">') + len('<div class="grid">')]
    head = re.sub(r"<!-- AUTO-GENERATED by examples/viz/gen_gallery\.py.*?-->\n?", "", head, flags=re.S)
    head = head.replace("<!doctype html>\n", "<!doctype html>\n" + BANNER + "\n", 1)

    figs, fig_divs, plots = [], [], []
    for idx, fig in enumerate(FIGURES):
        title, desc, full, args = fig[:4]
        prep = fig[4] if len(fig) > 4 else None
        sys.stderr.write(f"[{idx}] {title}: qsv viz {' '.join(args)}\n")
        figs.append(run_fig(qsv, args, prep))
        cls = "cell full" if full else "cell"
        gid = f"g{idx}"
        fig_divs.append(
            f'<figure class="{cls}"><figcaption><span class="t">{title}</span>'
            f'<span class="d">{desc}</span></figcaption><div id="{gid}" class="plot"></div></figure>'
        )
        plots.append(
            f'Plotly.newPlot("{gid}", FIGS[{idx}].data, FIGS[{idx}].layout || {{}}, '
            f'Object.assign({{responsive:true}}, FIGS[{idx}].config || {{}}));'
        )

    figs_json = "const FIGS = [" + ",".join(
        json.dumps(f, ensure_ascii=False, separators=(",", ":")) for f in figs) + "];"
    body = (
        head + "\n"
        + "\n".join(fig_divs) + "\n"
        + "</div>\n<script>\n"
        + figs_json + "\n"
        + "\n".join(plots) + "\n"
        + "</script>\n</body></html>\n"
    )
    with open(GALLERY, "w", encoding="utf-8") as fh:
        fh.write(body)
    cleanup_sidecars()
    sys.stderr.write(f"wrote {GALLERY} ({len(body)} bytes, {len(figs)} figures)\n")


if __name__ == "__main__":
    main()
