#!/usr/bin/env python3
"""Regenerate examples/viz/gallery.html from the current qsv binary.

`gallery.html` is a lightweight, CDN-plotly page rendering every `qsv viz`
chart type from the sample datasets in this directory. It is a checked-in
*artifact*; this script is the source of truth for how it's produced.

For each figure it runs the documented `qsv viz` command, extracts the figure
JSON object that plotly-rs emits (`Plotly.newPlot(graph_div, {...})`) from the
self-contained output, and reassembles them into one page that loads plotly from
the CDN (so the committed file stays small). The static scaffold (head / style /
header) is reused verbatim from the existing gallery, so re-running this only
changes figure content and order.

Usage (from the repo root), after changing viz output or the datasets:

    cargo build --bin qsv -F all_features
    python3 examples/viz/gen_gallery.py

Set QSV_BIN to point at a specific binary; otherwise target/{debug,release}/qsv
or a `qsv` on PATH is used. Re-run and commit gallery.html if the diff is what
you expect. The per-figure commands below are mirrored in README.md.
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

VIZ_DIR = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(VIZ_DIR))
GALLERY = os.path.join(VIZ_DIR, "gallery.html")
MARKER = "Plotly.newPlot(graph_div, "

BANNER = (
    "<!-- AUTO-GENERATED by examples/viz/gen_gallery.py — do not edit by hand.\n"
    "     Regenerate (from the repo root) after changing viz output or the datasets:\n"
    "       cargo build --bin qsv -F all_features && python3 examples/viz/gen_gallery.py\n"
    "-->"
)

# (title, description, full_width, [viz args]). Order matters: the full-width smart dashboards
# lead and close the contiguous run of individual chart types.
FIGURES = [
    ("smart dashboard", "Auto-profiled overview: correlation heatmap + box plots + frequency bars.",
     True, ["smart", "sales_sample.csv", "--max-charts", "8"]),
    ("smart dashboard (--smarter)",
     "Same auto-profiler with `--smarter`, which runs `qsv moarstats --advanced` itself to enrich "
     "the stats cache in one step: the bimodal monthly_spend column renders as a histogram (a box "
     "plot would hide its two peaks), and the skewed account_age_days box is annotated with its "
     "skew direction and outlier share.",
     True, ["smart", "customer_spend.csv", "--smarter", "--max-charts", "8"]),
    ("smart dashboard (--smarter, geospatial)",
     "One `qsv viz smart seismic_events.csv --smarter --theme plotly_dark --grid-cols 3` command, "
     "10 auto-chosen panels — nearly every "
     "panel type at once on a synthetic catalog of Japanese earthquakes. Things the raw table hides "
     "but the dashboard makes obvious: depth_km is <b>bimodal</b> (two populations — shallow "
     "interplate quakes ~20&nbsp;km and the deep Wadati-Benioff slab ~450&nbsp;km — so --smarter "
     "draws a histogram, not a box that would average the peaks away); the points trace Japan's "
     "subduction arcs on the map; magnitude vs felt_reports is almost perfectly correlated "
     "(r=0.95); magnitude and felt_reports are right-skewed with flagged outliers; and the "
     "magnitude-over-time trend spikes during a September aftershock sequence. Coordinate columns "
     "are shown on the map only, not re-charted as distributions. Rendered with the built-in "
     "<code>plotly_dark</code> theme.",
     True, ["smart", "seismic_events.csv", "--smarter", "--theme", "plotly_dark", "--grid-cols", "3"]),
    ("smart dashboard (geographic outliers)",
     "`qsv viz smart delivery_stops.csv` — delivery stops clustered in metro Denver with four "
     "bad-geocode strays. Points far from the cluster centroid (beyond the Tukey far-out fence of "
     "their distances) are flagged as geographic <b>outliers</b>: drawn as distinct amber markers, "
     "drawn outside the purple (filled) spatial-extent box, and excluded from the auto-zoom — so the "
     "default view stays tight on the core cluster. A second, dashed-magenta no-fill box marks the "
     "full extent (core + outliers), so the strays' span is legible once you zoom/pan out. In the "
     "full <code>qsv viz smart</code> HTML output the spatial-extent label calls them out — "
     "<i>Colorado, United States &mdash; 4 outliers (Wyoming, Kansas &amp; Nebraska)</i> — while "
     "strays within the core's own jurisdiction are folded back in silently instead.",
     True, ["smart", "delivery_stops.csv"]),
    ("bar", "Revenue by region (aggregated sum).",
     False, ["bar", "sales_sample.csv", "--x", "region", "--y", "revenue", "--agg", "sum"]),
    ("line", "Closing price over time.",
     False, ["line", "stock_prices.csv", "--x", "date", "--y", "close"]),
    ("scatter", "Units sold vs revenue.",
     False, ["scatter", "sales_sample.csv", "--x", "units_sold", "--y", "revenue"]),
    ("scatter (bubble)", "Units vs revenue; marker size = shipping cost, color = profit margin %.",
     False, ["scatter", "sales_sample.csv", "--x", "units_sold", "--y", "revenue",
             "--size", "shipping_cost", "--color", "profit_margin_pct"]),
    ("scatter3d", "Units vs revenue vs shipping cost in 3D; marker color = profit margin %.",
     False, ["scatter3d", "sales_sample.csv", "--x", "units_sold", "--y", "revenue",
             "--z", "shipping_cost", "--color", "profit_margin_pct"]),
    ("histogram", "Distribution of unit price.",
     False, ["histogram", "sales_sample.csv", "--x", "unit_price"]),
    ("box", "Spread of revenue (Tukey whiskers; points beyond the fences shown as outliers).",
     False, ["box", "sales_sample.csv", "--y", "revenue"]),
    ("box (grouped)", "Revenue spread per region — real Tukey whiskers + every (jittered) point overlaid (--box-points all).",
     False, ["box", "sales_sample.csv", "--y", "revenue", "--x", "region", "--box-points", "all"]),
    ("pie (donut)", "Revenue share by product category.",
     False, ["pie", "sales_sample.csv", "--x", "product_category", "--y", "revenue", "--donut"]),
    ("heatmap (correlation)", "Pearson correlation matrix over numeric columns.",
     False, ["heatmap", "sales_sample.csv"]),
    ("scatter (correlated pair)",
     "The most strongly correlated numeric pair (discount_pct vs profit_margin_pct, r=-0.99). "
     "viz smart auto-adds this as a drill-down beside the correlation heatmap.",
     False, ["scatter", "sales_sample.csv", "--x", "discount_pct", "--y", "profit_margin_pct"]),
    ("contour", "2D density of units sold vs revenue (binned into a 20x20 grid). viz smart uses "
     "this instead of the pair scatter for large datasets, where a scatter would overplot.",
     False, ["contour", "sales_sample.csv", "--x", "units_sold", "--y", "revenue", "--bins", "20"]),
    ("heatmap (pivot)", "Region x category grid of revenue.",
     False, ["heatmap", "sales_sample.csv", "--x", "region", "--y", "product_category", "--z", "revenue"]),
    ("candlestick", "OHLC price action.",
     False, ["candlestick", "stock_prices.csv", "--x", "date", "--ohlc-open", "open",
             "--high", "high", "--low", "low", "--close", "close"]),
    ("ohlc", "Open-high-low-close bars.",
     False, ["ohlc", "stock_prices.csv", "--x", "date", "--ohlc-open", "open",
             "--high", "high", "--low", "low", "--close", "close"]),
    ("sankey", "Web session funnel (duplicate edges aggregated).",
     False, ["sankey", "web_flows.csv", "--source", "source", "--target", "target", "--value", "sessions"]),
    ("radar", "Multi-axis brand comparison (per-axis mean per series).",
     False, ["radar", "product_ratings.csv", "--cols", "battery,camera,performance,display,value,design",
             "--series", "brand"]),
    ("map", "Earthquake points on token-free OpenStreetMap tiles; marker color = magnitude, size = depth.",
     False, ["map", "quakes.csv", "--lat", "lat", "--lon", "lon", "--color", "magnitude", "--size", "depth_km"]),
    ("map (density)", "DensityMapbox heatmap of the same points on a light Carto basemap.",
     False, ["map", "quakes.csv", "--lat", "lat", "--lon", "lon", "--density", "--style", "carto-positron"]),
    ("geo", "Same earthquakes on an offline natural-earth projection (no tiles, no token); marker "
     "color = magnitude. viz smart auto-uses this projection for global-extent coordinates.",
     False, ["geo", "quakes.csv", "--lat", "lat", "--lon", "lon", "--color", "magnitude",
             "--projection", "natural-earth"]),
    ("smart dashboard (time-series)",
     "Auto dashboard for stock_prices: a time-series trend panel (the first numeric column over the "
     "date) leads, alongside box-plot summaries of the OHLC columns.",
     True, ["smart", "stock_prices.csv", "--max-charts", "8"]),
]


def find_qsv():
    if os.environ.get("QSV_BIN"):
        return os.environ["QSV_BIN"]
    for rel in ("target/debug/qsv", "target/release/qsv"):
        cand = os.path.join(REPO, rel)
        if os.path.exists(cand):
            return cand
    found = shutil.which("qsv")
    if found:
        return found
    sys.exit("qsv binary not found: build it (cargo build --bin qsv -F all_features) or set QSV_BIN")


def scan_object(html, brace_start):
    """Brace-scan the balanced {...} object starting at brace_start; return (obj, end_index)."""
    assert html[brace_start] == "{", f"expected object at {brace_start}, got {html[brace_start]!r}"
    depth, in_str, esc = 0, False, False
    for i in range(brace_start, len(html)):
        c = html[i]
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            continue
        if c == '"':
            in_str = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return json.loads(html[brace_start:i + 1]), i + 1
    raise ValueError("unbalanced braces after newPlot marker")


def extract_fig_json(html):
    """The single grid-form figure object: `Plotly.newPlot(graph_div, {...})`."""
    obj, _ = scan_object(html, html.index(MARKER) + len(MARKER))
    return obj


def extract_inline_panels(html):
    """The inline-div smart dashboard form (used when a map panel forces it, or for >8 panels):
    a series of `Plotly.newPlot("qsv-viz-panel-N", {...})` calls, each a self-contained figure.
    Returns the list of panel objects, or None when the output isn't the inline form."""
    needle = 'Plotly.newPlot("qsv-viz-panel-'
    if needle not in html:
        return None
    panels, idx = [], 0
    while True:
        i = html.find(needle, idx)
        if i < 0:
            break
        obj, idx = scan_object(html, html.index("{", i))
        panels.append(obj)
    return panels


def run_fig(qsv, args):
    fd, out = tempfile.mkstemp(suffix=".html")
    os.close(fd)
    try:
        subprocess.run([qsv, "viz", *args, "-o", out], cwd=VIZ_DIR,
                       check=True, capture_output=True, text=True)
        with open(out, encoding="utf-8") as fh:
            html = fh.read()
    finally:
        os.unlink(out)
    panels = extract_inline_panels(html)
    if panels is not None:
        return {"panels": panels}          # inline multi-panel dashboard
    return {"fig": extract_fig_json(html)}  # single grid-form figure


def grid_cols(args):
    """The --grid-cols value from a smart dashboard's args (default 2)."""
    if "--grid-cols" in args:
        return int(args[args.index("--grid-cols") + 1])
    return 2


def cleanup_sidecars():
    # `viz smart` writes a stats cache next to the CSV; `--smarter` (via its internal
    # `moarstats --advanced`) also auto-creates an `.idx` index. Don't leave either in the tree
    # (the committed datasets ship without them).
    for f in os.listdir(VIZ_DIR):
        if ".stats.csv" in f or ".stats.jsonl" in f or f.endswith(".idx"):
            os.unlink(os.path.join(VIZ_DIR, f))


def main():
    qsv = find_qsv()
    # reuse the existing scaffold verbatim: everything up to and including `<div class="grid">`,
    # minus any previous banner (re-added below so it stays a single, current copy)
    with open(GALLERY, encoding="utf-8") as fh:
        existing = fh.read()
    head = existing[: existing.index('<div class="grid">') + len('<div class="grid">')]
    head = re.sub(r"<!-- AUTO-GENERATED by examples/viz/gen_gallery\.py.*?-->\n?", "", head, flags=re.S)
    head = head.replace("<!doctype html>\n", "<!doctype html>\n" + BANNER + "\n", 1)

    figs, fig_divs, plots = [], [], []
    for idx, fig in enumerate(FIGURES):
        title, desc, full, args = fig
        sys.stderr.write(f"[{idx}] {title}: qsv viz {' '.join(args)}\n")
        result = run_fig(qsv, args)
        gid = f"g{idx}"
        if "panels" in result:
            # inline multi-panel dashboard: store the panel list and render a nested sub-grid of
            # independent plots (one <div> + newPlot per panel) inside a single full-width cell
            panels = result["panels"]
            figs.append(panels)
            cols = grid_cols(args)
            cells = "".join(
                f'<div id="{gid}-p{k}" style="height:340px"></div>' for k in range(len(panels)))
            fig_divs.append(
                f'<figure class="cell full"><figcaption><span class="t">{title}</span>'
                f'<span class="d">{desc}</span></figcaption>'
                f'<div style="display:grid;grid-template-columns:repeat({cols},minmax(0,1fr));'
                f'gap:14px">{cells}</div></figure>'
            )
            for k in range(len(panels)):
                plots.append(
                    f'Plotly.newPlot("{gid}-p{k}", FIGS[{idx}][{k}].data, '
                    f'FIGS[{idx}][{k}].layout || {{}}, '
                    f'Object.assign({{responsive:true}}, FIGS[{idx}][{k}].config || {{}}));'
                )
        else:
            figs.append(result["fig"])
            cls = "cell full" if full else "cell"
            fig_divs.append(
                f'<figure class="{cls}"><figcaption><span class="t">{title}</span>'
                f'<span class="d">{desc}</span></figcaption><div id="{gid}" class="plot"></div>'
                f'</figure>'
            )
            plots.append(
                f'Plotly.newPlot("{gid}", FIGS[{idx}].data, FIGS[{idx}].layout || {{}}, '
                f'Object.assign({{responsive:true}}, FIGS[{idx}].config || {{}}));'
            )

    figs_json = "const FIGS = [" + ",".join(
        json.dumps(f, ensure_ascii=False, separators=(",", ":")) for f in figs) + "];"
    body = (
        head + "\n"
        + "\n".join(fig_divs) + "\n"
        + "</div>\n<script>\n"
        + figs_json + "\n"
        + "\n".join(plots) + "\n"
        + "</script>\n</body></html>\n"
    )
    with open(GALLERY, "w", encoding="utf-8") as fh:
        fh.write(body)
    cleanup_sidecars()
    sys.stderr.write(f"wrote {GALLERY} ({len(body)} bytes, {len(figs)} figures)\n")


if __name__ == "__main__":
    main()
