[default]
extend-ignore-identifiers-re = ["wrk", "flate", "ND", "typ", "ful"]

[default.extend-identifiers]
# typos in third-party code/libraries
WrittingCSV = "WrittingCSV"
seperator   = "seperator"

[default.extend-words]
# these are false positives in data/examples
ALLE          = "ALLE"
ba            = "ba"
Environnement = "Environnement"
fo            = "fo"
hel           = "hel"
inout         = "inout"
UE            = "UE"
seeked        = "seeked"
DNE           = "DNE"
Generice      = "Generice"
Portugese     = "Portugese"
ACI           = "ACI"
consts        = "consts"
Caf           = "Caf"
unparseable   = "unparseable"
mis           = "mis"
nd            = "nd"
Pn            = "Pn"
tripel        = "tripel"
sems          = "sems"

[files]
extend-exclude = [
    "*.csv",
    "*.geojson",
    "*.ipynb",
    "*.jsonl",
    "*.lua",
    "*.pynb",
    "*.ssv",
    "*.tab",
    "nyc311-describegpt*.*",
    "docs/describegpt/*",
    "docs/whirlwind_tour.md",
    "*.py",
    "test_clean.rs",
    "smart_world_choropleth.html",
    "smart_nyc311.html",
    "pitt311data.html",
]
