[advisories]
yanked = "deny"
ignore = [
  # THESE ISSUES ARE ALLOW-LISTED HERE TO SILENCE THE CI TEMPORARILY
  # THESE ISSUES NEED TO BE FIXED

  # error[vulnerability]: Quadratic run time when checking a start tag for duplicate attribute names in quick-xml
  "RUSTSEC-2026-0194",
  # error[vulnerability]: Unbounded namespace-declaration allocation in `NsReader` enables memory-exhaustion denial of service in quick-xml
  "RUSTSEC-2026-0195",
]
