```sql
-- Generated by qsv's describegpt command using openai/gpt-oss-20b on 2025-08-26T10:48:07.710668+00:00
-- This query returns the number of complaints for each Complaint Type,
-- grouped by Borough and calendar year (extracted from Created Date).
-- It uses DuckDB's read_csv table function to ingest the CSV file.
-- Fields are quoted because they contain spaces.
SELECT
  "Borough",
  extract(year FROM CAST("Created Date" AS TIMESTAMP)) AS year,
  "Complaint Type",
  COUNT(*) AS complaint_count
FROM read_csv('/tmp/NYC_311_SR_2010-2020-sample-1M.csv', header=true)
WHERE "Created Date" IS NOT NULL
  AND "Borough" IS NOT NULL
GROUP BY
  "Borough",
  year,
  "Complaint Type"
ORDER BY
  "Borough",
  year,
  complaint_count DESC;
```
