//! Tool definitions embedded in the binary (issue #4638).
//!
//! The tool definitions (`docs/tool-definitions/qsv-<cmd>.json`, one per command, a superset
//! of the curated MCP skills in `.claude/skills/qsv/`) and help Markdown (`docs/help/<cmd>.md`)
//! are generated by `--update-mcp-skills` and `--generate-help-md`,
//! which parse the qsv source tree and so only work inside a repo checkout. `build.rs`
//! embeds the committed copies instead, so any installed qsv/qsvmcp can hand out definitions
//! that match its own version via `--tool-definition` and `--export-tool-definitions`.

use std::{collections::HashSet, fs, io::Write, path::Path};

use crate::CliResult;

include!(concat!(env!("OUT_DIR"), "/embedded_tool_defs.rs"));

/// Help Markdown that isn't tied to a single command and is always exported.
const HELP_INDEX: &str = "TableOfContents";

/// The command names compiled into this binary, taken from the first token of each line of
/// the `--list` text so this shares its feature gating instead of duplicating it.
pub fn installed_commands(enabled_commands: &str) -> HashSet<&str> {
    enabled_commands
        .lines()
        .filter_map(|line| line.split_whitespace().next())
        .collect()
}

fn lookup<'a>(table: &'a [(&str, &str)], key: &str) -> Option<&'a str> {
    table.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)
}

/// Print the embedded JSON tool definition for `command` to stdout.
pub fn print_tool_definition(command: &str, installed: &HashSet<&str>) -> CliResult<()> {
    if !installed.contains(command) {
        return fail_clierror!(
            "\"{command}\" is not a command in this qsv binary. Run `qsv --list` to see the \
             installed commands."
        );
    }
    let Some(json) = lookup(TOOL_DEFS, command) else {
        return fail_clierror!(
            "\"{command}\" has no embedded tool definition. Run `qsv {command} --help` for its \
             usage text."
        );
    };
    std::io::stdout().write_all(json.as_bytes())?;
    Ok(())
}

/// Write the embedded tool definitions for the installed commands into `dir`:
/// `tool_definitions/qsv-<cmd>.json`, `help/<cmd>.md` (plus the help table of contents) and a
/// `manifest.json` recording the qsv version they were built with and which of the commands
/// are in the curated MCP skill set.
pub fn export_tool_definitions(dir: &str, installed: &HashSet<&str>) -> CliResult<()> {
    let out_dir = Path::new(dir);
    let defs_dir = out_dir.join("tool_definitions");
    let help_dir = out_dir.join("help");
    fs::create_dir_all(&defs_dir)?;
    fs::create_dir_all(&help_dir)?;

    let mut defs = Vec::new();
    for (cmd, json) in TOOL_DEFS.iter().filter(|(cmd, _)| installed.contains(cmd)) {
        fs::write(defs_dir.join(format!("qsv-{cmd}.json")), json)?;
        defs.push(*cmd);
    }
    let mcp_skills: Vec<&str> = MCP_SKILLS
        .iter()
        .copied()
        .filter(|cmd| installed.contains(cmd))
        .collect();

    let mut help = Vec::new();
    for (name, md) in HELP_MDS
        .iter()
        .filter(|(name, _)| *name == HELP_INDEX || installed.contains(name))
    {
        fs::write(help_dir.join(format!("{name}.md")), md)?;
        help.push(*name);
    }

    // a reused export dir may hold files from another qsv version or feature set; drop the
    // ones this export didn't write so the directory matches manifest.json
    remove_stale(&defs_dir, "qsv-", ".json", &defs)?;
    remove_stale(&help_dir, "", ".md", &help)?;

    let mut commands: Vec<&str> = installed.iter().copied().collect();
    commands.sort_unstable();
    let manifest = serde_json::json!({
        "qsv_version": env!("CARGO_PKG_VERSION"),
        "binary": env!("CARGO_BIN_NAME"),
        "commands": commands,
        "tool_definitions": defs,
        "mcp_skills": mcp_skills,
        "help": help,
    });
    fs::write(
        out_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest)? + "\n",
    )?;

    eprintln!(
        "Exported {} tool definition(s) to {} and {} help file(s) to {}",
        defs.len(),
        defs_dir.display(),
        help.len(),
        help_dir.display()
    );
    Ok(())
}

/// Remove files in `dir` named `prefix<key>suffix` whose key is not in `keep`. Only files
/// matching the export's own naming pattern are touched.
fn remove_stale(dir: &Path, prefix: &str, suffix: &str, keep: &[&str]) -> CliResult<()> {
    for entry in fs::read_dir(dir)?.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        let Some(key) = name
            .strip_prefix(prefix)
            .and_then(|n| n.strip_suffix(suffix))
        else {
            continue;
        };
        if !keep.contains(&key) && entry.path().is_file() {
            fs::remove_file(entry.path())?;
        }
    }
    Ok(())
}
