//! Tool definitions and help Markdown generated by the running binary from its own USAGE text
//! (issue #4638), so they always match the installed qsv version and feature set.
//!
//! The generators behind `--update-mcp-skills` and `--generate-help-md` need a few inputs
//! besides USAGE: the README command table and legend, and each command's args struct. Those
//! are embedded at build time as raw fragments (see `embed_command_metadata` in `build.rs`)
//! and fed to the same generator functions, so `qsv <cmd> --help --format json|md` prints
//! exactly what the in-repo generators write to `.claude/skills/qsv/` and `docs/help/`.
//!
//! Only declared in `main.rs`, so only the qsv and qsvmcp binaries have it.

use std::{fs, io::Write, path::Path};

use serde::Deserialize;
use strum::VariantNames;

use crate::{
    CliError, CliResult, Command,
    help_markdown_gen::{self, CommandInfo},
    mcp_skills_gen,
};

include!(concat!(env!("OUT_DIR"), "/cmd_meta.rs"));

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum HelpFormat {
    Json,
    Md,
}

/// `Some(format)` when the command's arguments ask for help (`-h`/`--help`) together with
/// `--format json|md`. Plain `--help`, or `--format` without a help flag (several commands
/// have a `--format` option of their own), returns `None` and is left to the command.
pub fn help_format(args: &[&str]) -> CliResult<Option<HelpFormat>> {
    if !args.iter().any(|a| *a == "-h" || *a == "--help") {
        return Ok(None);
    }
    let mut format = None;
    for (i, arg) in args.iter().enumerate() {
        if let Some(value) = arg.strip_prefix("--format=") {
            format = Some(value);
        } else if *arg == "--format" {
            format = Some(args.get(i + 1).copied().unwrap_or_default());
        }
    }
    match format {
        None => Ok(None),
        Some("json") => Ok(Some(HelpFormat::Json)),
        Some("md") => Ok(Some(HelpFormat::Md)),
        Some(other) => fail_incorrectusage_clierror!(
            "invalid --help --format \"{other}\". Valid formats: json, md."
        ),
    }
}

/// Print one command's tool definition or help Markdown to stdout.
pub fn print(invocation_name: &str, usage: &str, format: HelpFormat) -> CliResult<()> {
    let commands = readme_commands()?;
    let rendered = render(&commands, invocation_name, usage, format, &legend())?;
    std::io::stdout().write_all(rendered.as_bytes())?;
    Ok(())
}

/// Write `<dir>/tool-definitions/qsv-<cmd>.json`, `<dir>/help/<cmd>.md` (plus
/// `TableOfContents.md`) and `<dir>/manifest.json` for every command in this binary.
pub fn export(dir: &str) -> CliResult<()> {
    let commands = readme_commands()?;
    let legend = legend();
    // README table order, then any installed command the table doesn't list
    let mut installed: Vec<(CommandInfo, &'static str)> = commands
        .iter()
        .filter_map(|info| installed_usage(&info.invocation_name).map(|u| (info.clone(), u)))
        .collect();
    for name in Command::VARIANTS {
        if !commands.iter().any(|c| c.invocation_name == *name)
            && let Some(usage) = installed_usage(name)
        {
            installed.push((CommandInfo::unlisted(name), usage));
        }
    }

    let out_dir = Path::new(dir);
    let defs_dir = out_dir.join("tool-definitions");
    let help_dir = out_dir.join("help");
    fs::create_dir_all(&defs_dir)?;
    fs::create_dir_all(&help_dir)?;

    for (info, usage) in &installed {
        let name = &info.invocation_name;
        let json = render(&commands, name, usage, HelpFormat::Json, &legend)?;
        fs::write(defs_dir.join(format!("qsv-{name}.json")), json)?;
        let md = render(&commands, name, usage, HelpFormat::Md, &legend)?;
        fs::write(help_dir.join(format!("{name}.md")), md)?;
    }
    let installed_infos: Vec<CommandInfo> = installed.iter().map(|(i, _)| i.clone()).collect();
    fs::write(
        help_dir.join("TableOfContents.md"),
        help_markdown_gen::generate_table_of_contents(&installed_infos, README_FRAGMENT, &legend),
    )?;

    // the MCP set is keyed by source-file name (`enumerate`), the files by invocation (`enum`)
    let mcp_set = mcp_skills_gen::mcp_skill_commands();
    let commands_list: Vec<&str> = installed
        .iter()
        .map(|(i, _)| i.invocation_name.as_str())
        .collect();
    let mcp_skills: Vec<&str> = installed
        .iter()
        .filter(|(i, _)| mcp_set.contains(&i.source_file.as_str()))
        .map(|(i, _)| i.invocation_name.as_str())
        .collect();
    let manifest = serde_json::json!({
        "qsv_version": env!("CARGO_PKG_VERSION"),
        "binary": env!("CARGO_BIN_NAME"),
        "commands": commands_list,
        "mcp_skills": mcp_skills,
    });
    fs::write(
        out_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest)? + "\n",
    )?;

    eprintln!(
        "Exported {} tool definition(s) to {} and help Markdown to {}",
        installed.len(),
        defs_dir.display(),
        help_dir.display()
    );
    Ok(())
}

/// The USAGE text of `invocation_name` if it is a command compiled into this binary. A
/// feature-gated-out `Command` variant doesn't exist, so it fails to deserialize.
fn installed_usage(invocation_name: &str) -> Option<&'static str> {
    let de = serde::de::value::StrDeserializer::<serde::de::value::Error>::new(invocation_name);
    Command::deserialize(de).ok()?.usage()
}

fn readme_commands() -> CliResult<Vec<CommandInfo>> {
    help_markdown_gen::commands_from_readme(README_FRAGMENT).map_err(CliError::Other)
}

fn legend() -> Vec<(String, String)> {
    help_markdown_gen::parse_legend(README_FRAGMENT)
}

/// (source path, args fragment) embedded for the command whose source file stem is `stem`.
fn command_source(stem: &str) -> Option<(&'static str, &'static str)> {
    CMD_SOURCES
        .iter()
        .find(|(s, ..)| *s == stem)
        .map(|(_, path, args_src)| (*path, *args_src))
}

fn render(
    commands: &[CommandInfo],
    invocation_name: &str,
    usage: &str,
    format: HelpFormat,
    legend: &[(String, String)],
) -> CliResult<String> {
    // a command missing from the README table (e.g. qsvmcp's `log`) still gets a definition,
    // with its description taken from USAGE and no emoji markers
    let unlisted;
    let info = match commands
        .iter()
        .find(|c| c.invocation_name == invocation_name)
    {
        Some(info) => info,
        None => {
            unlisted = CommandInfo::unlisted(invocation_name);
            &unlisted
        },
    };
    let (source_path, args_src) = command_source(&info.source_file).ok_or_else(|| {
        CliError::Other(format!(
            "no embedded source metadata for `{invocation_name}`"
        ))
    })?;
    match format {
        HelpFormat::Json => {
            mcp_skills_gen::tool_definition_json(invocation_name, usage, README_FRAGMENT, args_src)
                .map_err(CliError::Other)
        },
        HelpFormat::Md => Ok(help_markdown_gen::command_markdown(
            usage,
            info,
            source_path,
            legend,
            args_src,
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn help_format_needs_a_help_flag() {
        assert_eq!(help_format(&["--format", "json"]).unwrap(), None);
        assert_eq!(help_format(&["--help"]).unwrap(), None);
        assert_eq!(
            help_format(&["--help", "--format", "json"]).unwrap(),
            Some(HelpFormat::Json)
        );
        assert_eq!(
            help_format(&["--format=md", "-h"]).unwrap(),
            Some(HelpFormat::Md)
        );
        assert!(help_format(&["-h", "--format", "yaml"]).is_err());
        assert!(help_format(&["-h", "--format"]).is_err());
    }

    #[test]
    fn every_installed_command_has_embedded_metadata() {
        let commands = readme_commands().unwrap();
        let mut installed = 0;
        for info in &commands {
            if installed_usage(&info.invocation_name).is_some() {
                installed += 1;
                assert!(
                    command_source(&info.source_file).is_some(),
                    "{} has no embedded args fragment",
                    info.invocation_name
                );
            }
        }
        assert!(installed > 20, "only {installed} installed commands found");
    }
}
