name: Publish Debian Package

on:
  release:
    types: [published]

env:
  QSV_KIND: prebuilt

jobs:                
  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev
          cargo install cargo-deb

      - name: Build all Debian packages
        id: build
        run: |
          chmod +x .scripts/build_all_debs.sh
          echo "DEB_PATHS=$(.scripts/build_all_debs.sh)" >> $GITHUB_OUTPUT

      - name: Upload Debian Packages as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages
          path: ${{ steps.build.outputs.DEB_PATHS }}