name: Linux Nightly using Polars pinned nightly version

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6.0.0
      with:
        python-version: '3.13'
    - name: apt-get update Ubuntu, libwayland-dev
      run: |
        sudo apt-get update
        sudo apt-get install libwayland-dev
    - name: Install and Run Redis
      run: |
        sudo apt-get install redis-server
        sudo service redis-server start
    - name: Installing Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        # get nightly version Polars is using
        # https://github.com/pola-rs/polars/blob/main/rust-toolchain.toml
        toolchain: nightly
        components: rust-src
        target: x86_64-unknown-linux-gnu
    - name: Run tests
      # env:
      #   RUSTFLAGS: -C target-cpu=native
      run: cargo test --verbose --locked --features=apply,fetch,foreach,geocode,luau,python,feature_capable,nightly,polars,lens
