name: qsvdp - Datapusher+ optimized qsv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ci-qsvdp-tests-${{ github.ref }}-1
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: apt-get update Ubuntu, libwayland-dev
      run: |
        sudo apt-get update
        sudo apt-get install libwayland-dev
    - name: Installing Rust toolchain
      uses: dtolnay/rust-toolchain@1.90.0
    - name: Setup Rust-cache
      uses: Swatinem/rust-cache@v2
      with:
        key: qsvdp-cache
    - name: Run tests
      env:
        RUSTFLAGS: -C target-cpu=native
      run: cargo test --verbose --locked --features=datapusher_plus,luau
