name: Windows Lite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ci-windows-lite-tests-${{ github.ref }}-1
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - name: Installing Rust toolchain
      uses: dtolnay/rust-toolchain@1.100.0
    - name: Setup Rust-cache
      uses: Swatinem/rust-cache@v2
      with:
        key: qsv-winlitecache
    - name: Run tests
      env:
        RUSTFLAGS: -C target-cpu=native
      run: cargo test --verbose --locked --features=lite
